export const emojis = {
 happy: "🌼 ✨ 💖 😊",
  sad: "🌧️ 📖 🕯️ 😔",
 dreamy: "🌙 🫧 ⭐ 💭",
  aesthetic: "🧃 🌸 📷 🎀",
  soft: "🧸 🕊️ 🍥 🤍",
  cool: "🖤 😎 🎧 💿",
  cozy: "🧺 ☕ 🧦 🕯️",
fairycore: "🧚 🌸 🍄 ✨",
angelic: "👼 ☁️ ✨ 🕊️",
baddie: "💅 💖 🔥 👑",
cottagecore: "🍓 🧺 🕯️ 📖",
glowup: "🦋 💫 ✨ 👠",
witchy: "🔮 🌙 🕯️ 🐈‍⬛",
techie: "💻 📱 📷 🌐",
excited: "🎉 💃 💫 🤩",
angry: "😤 🔥 💢 🙃",
fear: "😨 👁️‍🗨️ 🕷️ 🌫️",
irritated: "😒 🙄 💅 🔕",
surprise: "😲 🎁 ✨ 🎉",
calm: "🧘 🕊️ ☁️ 🍃",
depression: "😔 🌧️ 📖 🕯️",
anxiety: "😰 🫣 💭 🌫️",
hot: "🔥 😎 💋 🌶️",
cold: "❄️ 🧊 🥶 🌬️",
};

export const quotes = [
  "living slowly & glowing gently",
  "in love with the quiet moments",
  "a heart made of clouds and calm",
"becoming the version I dreamed of",
"soft spells & full moons",
"She blooms in silence, and glows without trying.",
"Rooted in softness, she grew with grace.",
"Not made to blend in, she paints her own sky.",
"Stars stitched to her skin, dreams folded in her pockets.",
"She's not perfect, she's poetry in motion.",
"Her peace is louder than their opinions.",
"Even in the shadows, she finds her spark.",
"Too soft for this world, yet strong enough to stay.",
"There's glitter in her stillness, and fire in her quiet.",
"She's everything they said she couldn't be, wrapped in pastel.",
"Hearts like hers don't break, they bend into beauty.",
"A little wild, a little wonder.",
"She's the kind of magic, you don't explain.",
"Loving slowly, glowing softly.",
"Falling apart beautifully, like glitter in the wind.",
"magic in the mundane",
"stardust with structure",
"aligned but unpredictable",
"moonlit & mysterious",
"not perfect, just evolving",
"soft heart, sharp focus",
"not your average sparkle",
"pretty but not to be played with",
"growing gently in my own direction",
"soft as moss, strong as stone",
"peace over performance",
"grounded but glowing",
"matching energy, not effort",
"rising quietly, glowing loudly",
"made of growth and glitter",
"wrapped in light, walking gently"
];
